Added LABEL grid failover, removed non-array SGE, enhanced resource management.

diff --git a/LABEL b/LABEL
--- a/LABEL
+++ b/LABEL
@@ -7,7 +7,7 @@
 
 PROGRAM="LABEL"
 YEAR="2016"
-VERSION="v0.5.1"
+VERSION="v0.5.2"
 AUTHOR="Samuel S. Shepard"
 EMAIL="vfn4@cdc.gov"
 AFFIL="Centers for Disease Control & Prevention"
@@ -97,7 +97,7 @@ function print_usage() {
 	echo -e "\t\t-T\tDo TRAINING again instead of using classifier files."
 	echo -e "\t\t-A\tDo ALIGNMENT of re-annotated fasta file (sorted by clade) & build its ML tree."
 	echo -e "\t\t-C\tDo CONTROL alignment & ML tree construction."
-	echo -e "\t\t-E\tSGE clustering option. Use 1 for SGE, 2 for SGE with array jobs, else local."
+	echo -e "\t\t-E\tSGE clustering option. Use 1 or 2 for SGE with array jobs, else local."
 	echo -e "\t\t-R\tNo RECURSIVE prediction. Limits scope, useful with -L option."
 	echo -e "\t\t-D\tNo DELETION of extra intermediary files."
 	echo -e "\t\t-S\tShow available protein modules."
@@ -130,7 +130,6 @@ function check_prgm() {
 	command -v $1 >/dev/null 2>&1 || { echo "`basename $0` ERROR: Program '$1' not found, please check your PATH or install it." >&2; exit 1; }
 }
 
-
 # Check for programs
 check_prgm zip
 check_prgm cut
@@ -139,7 +138,8 @@ check_prgm perl
 check_prgm /usr/bin/env
 
 # PROCESS BASH OPTIONS #
-P=12		# MAX CONCURRENT PARALLEL 
+LOCAL_PROC=16	# MAX CONCURRENT PARALLEL 
+GRID_PROC=128	# MAX CONCURRENT GRID PROCESSORS
 DO_TRAIN=0	# Use original data for training.
 DO_CONTROL=0	# Control tree computation (for debugging)
 NO_RECURSION=0	# Do not use recursion.
@@ -151,7 +151,6 @@ DO_OUT=0
 LINEAGE_PATH=""
 OUTPUT_DIR=`pwd`
 USE_SGE=0	# use SGE loosely
-USE_ARRAY=0	# use SGE arrays
 CLUSTER_OPT=0	# clustering option
 
 mafft=mafft
@@ -228,10 +227,10 @@ if [ $DO_WEB -eq 1 -a $DO_OUT -eq 1 ];then
 	exit 1
 fi
 
-if [ $CLUSTER_OPT -eq 1 ];then
+
+SEQ_LIMIT=100
+if [ "$CLUSTER_OPT" -gt 0 ];then
 	USE_SGE=1
-elif [ $CLUSTER_OPT -eq 2 ];then
-	USE_ARRAY=1
 fi
 
 # VARIABLES & PATHS #
@@ -247,6 +246,7 @@ muscle=$bin/muscle_$OS
 FastTreeMP=$bin/FastTreeMP_$OS
 modelfromalign=$bin/modelfromalign_$OS
 shogun=$bin/shogun_$OS
+PARALLEL="$bin/parallel --no-notice"
 
 
 if [ $DO_WEB -eq 0 ];then
@@ -283,30 +283,6 @@ if [ ! -d $tnpath ];then
 	echo -n "`basename $0` ERROR: module '$module' does not exist. Try: LABEL -S"
 	err_test 1	
 fi
-
-
-# FNC - SCORE_LINEAGE #
-# Scores sequences using a particular HMM for a lineage.
-function scoreLineageSGE() {
-	local ppath=$1
-	local m=$2
-	local level=$3
-	local db=$ppath/${project}_${level}.fas
-	local run=`basename $m .mod`
-	local mpath=`dirname $m`
-	local name=`date '+%s'`
-	local name="L`perl -e 'print int(rand(999999))'`${name: -8}"
-
-	cd $ppath
-	if [ -r $mpath/null.mod ];then
-		local cmd="$hmmscore $run -db $db -modelfile $m -subtract_null 0 && $bin/parseScores.pl $ppath/$run.dist > $ppath/$run.tab"
-	else
-		local cmd="$hmmscore $run -db $db -modelfile $m && $bin/parseScores.pl $ppath/$run.dist > $ppath/$run.tab"
-	fi
-
-	qsub -N $name -cwd -b y -j y -o $name.o "$cmd" > /dev/null 2>&1
-	echo "$name"
-}
 
 # FNC - SCORE_LINEAGE #
 # Scores sequences using a particular HMM for a lineage.
@@ -372,141 +348,102 @@ function doAnalysis() {
 	local tnpath=$3
 	local grouping=$4
 	local level=$5
+	local script=$ppath/${level}.tmp
 	local m
 	local joblist
 	local check
 	local c
-	local n=`grep '>' $ppath/${project}_${level}.fas -c`
 
 	# Concurrency limiting courtesy "tangens"
-	# http://stackoverflow.com/questions/1537956/bash-limit-the-number-of-concurrent-jobs
 	rm $ppath/${project}.tab.tmp >/dev/null 2>&1
 	[ -d $mpath/x-rev -a ! -d $ppath/x-rev ] && mkdir $ppath/x-rev
 
-	if [ $USE_ARRAY -eq 1 -a $n -gt 99 ];then
-		local g=1
-		if [ $n -gt 2000 ];then
-			g=20
-		else
-			g=$(expr $n / 100 + 1)
-		fi
-
-		if [ -r $mpath/null.mod ];then
-			local -a mods=($mpath/null.mod $mpath/*hmm.mod)
-		elif [ -d $mpath/x-rev ];then
-			local -a mods=($mpath/*hmm.mod $mpath/x-rev/*hmm.mod)
-		else
-			local -a mods=($mpath/*hmm.mod)
-		fi
-
-		local M=${#mods[@]}
-		local A=$(expr $M \* $g)
-		[ $A -gt 279 ] && g=$(expr 280 / $M + 1)
-		
-		$bin/interleavedSamples.pl -X tmpp -G $g $ppath/${project}_${level}.fas $ppath/leaf > /dev/null 2>&1
-
-		echo '#!/bin/bash' > $ppath/$level.tmp.sh	
-		echo "LANG=$LANG" >> $ppath/$level.tmp.sh
-		echo 'shopt -u nocaseglob;shopt -u nocasematch' >> $ppath/$level.tmp.sh
-		echo 'ID=`expr $SGE_TASK_ID - 1`' >> $ppath/$level.tmp.sh
-		echo 'm=`expr $ID / '"$g"'`' >> $ppath/$level.tmp.sh
-		echo 'i=`expr $ID % '"$g"' + 1`' >> $ppath/$level.tmp.sh
-		echo 'l=`printf %04d $i`' >> $ppath/$level.tmp.sh
-		echo "cd $ppath" >> $ppath/$level.tmp.sh
-		echo 'db="'"$ppath/"'leaf_${l}.tmpp"' >> $ppath/$level.tmp.sh
-		
-		# if special null models
-		if [ -r $mpath/null.mod ];then
-			echo "declare -a mods=($mpath/null.mod $mpath/*hmm.mod)" >> $ppath/$level.tmp.sh
-			echo 'run="`basename ${mods[$m]} .mod`_$l"' >> $ppath/$level.tmp.sh
-			echo "$hmmscore "'$run -db $db -modelfile ${mods[$m]} -subtract_null 0' >> $ppath/$level.tmp.sh
-		elif [ -d $mpath/x-rev ];then
-			echo "declare -a mods=($mpath/*hmm.mod $mpath/x-rev/*hmm.mod)" >> $ppath/$level.tmp.sh
-			echo 'pat=$(dirname ${mods[$m]});pat=$(basename $pat);[[ "$pat" == "x-rev" ]] && cd x-rev' >> $ppath/$level.tmp.sh
-			echo 'run="`basename ${mods[$m]} .mod`_$l"' >> $ppath/$level.tmp.sh
-			echo "$hmmscore "'$run -db $db -modelfile ${mods[$m]} -dpstyle 1 -subtract_null 1' >> $ppath/$level.tmp.sh
-		else
-			echo "declare -a mods=($mpath/*hmm.mod)" >> $ppath/$level.tmp.sh
-			echo 'run="`basename ${mods[$m]} .mod`_$l"' >> $ppath/$level.tmp.sh
-			echo "$hmmscore "'$run -db $db -modelfile ${mods[$m]}' >> $ppath/$level.tmp.sh
-		fi
-		local a=`expr $g \* ${#mods[@]}`
-
-		qsub -q all.q -t 1-$a:1 -sync y -j y -o $ppath/$level.o $ppath/$level.tmp.sh > /dev/null 2>&1
-		(( $DO_WEB )) || echo -n '...'
-
-		local run=""
-		for m in "${mods[@]}";do
-			run=$(basename $m .mod)
-			$bin/parseScores.pl $ppath/${run}_????.dist > $ppath/$run.tab
-			[ -d $ppath/x-rev ] && $bin/parseScores.pl $ppath/x-rev/${run}_????.dist > $ppath/x-rev/$run.tab
-		done
-
-		# custom clean-up
-		rm $ppath/*_hmm_????.dist $ppath/$level.tmp.sh $ppath/*.tmpp $ppath/null_????.dist > /dev/null 2>&1
-
-	elif [ $USE_SGE -eq 1 -a $n -gt 49 ];then
-		[ -d $mpath/x-rev ] && echo "$(basename $) ERROR: x-rev not implemented for option: -E 1" && err_test 1
-
-		# if special null models
-		if [ -r $mpath/null.mod ];then
-			joblist=$(scoreLineageSGE $ppath $mpath/null.mod $level)
-		fi
-
-		# for regular models
-		for m in $mpath/*hmm.mod;do
-			if [ "$joblist" == "" ];then
-				joblist=$(scoreLineageSGE $ppath $m $level)
-			else
-				joblist="${joblist},$(scoreLineageSGE $ppath $m $level)"
-			fi
-		done
-		qsub -sync y -j y -b y -o $level.o -cwd -hold_jid "$joblist" "sleep 0" > /dev/null 2>&1
-		(( $DO_WEB )) || echo -n '...'
-
+	local HMMSCORE_OPTS=""
+	if [ -r $mpath/null.mod ];then
+		local -a modList=($mpath/null.mod $mpath/*hmm.mod)
+		HMMSCORE_OPTS=" -subtract_null 0"
+	elif [ -d $mpath/x-rev ];then
+		local -a modList=($mpath/*hmm.mod $mpath/x-rev/*hmm.mod)
+		HMMSCORE_OPTS=" -dpstyle 1 -subtract_null 1"
 	else
-		# if special null models
-		if [ -r $mpath/null.mod ];then
-			joblist=($(jobs -p))
-			while (( ${#joblist[*]} >= $P ))
-			do
-				sleep 0.5
-				joblist=($(jobs -p))
-			done
-			(( $DO_WEB )) || echo -n '.'
-			scoreLineage $ppath $mpath/null.mod $level $ppath/${project}_${level}.fas &
-		fi
-
-		# for regular models
-		for m in $mpath/*hmm.mod;do
-			joblist=($(jobs -p))
-			while (( ${#joblist[*]} >= $P ))
-			do
-				sleep 0.5
-				joblist=($(jobs -p))
-			done
-			(( $DO_WEB )) || echo -n '.'
-			scoreLineage $ppath $m $level $ppath/${project}_${level}.fas &
-		done
-		wait
-
-		if [ -d $mpath/x-rev ];then
-			for m in $mpath/x-rev/*hmm.mod;do
-				joblist=($(jobs -p))
-				while (( ${#joblist[*]} >= $P ))
-				do
-					sleep 0.5
-					joblist=($(jobs -p))
-				done
-				(( $DO_WEB )) || echo -n '.'
-				scoreLineage $ppath/x-rev $m $level $ppath/${project}_${level}.fas &
-			done
-			wait
-		fi
-
-		# custom clean-up
-		rm $ppath/*_hmm.dist
+		local -a modList=($mpath/*hmm.mod)
 	fi
+
+	# number of modules, sequences, and groups
+	local mods=${#modList[@]}
+	local seqs=$(grep '>' $ppath/${project}_${level}.fas -c)
+	local procs=$LOCAL_PROC
+	local doGrid=0
+	if [ "$USE_SGE" -eq 1 -a "$seqs" -ge "$SEQ_LIMIT" ];then
+		procs=$GRID_PROC
+		doGrid=1
+	fi
+
+	local groups=$(expr $seqs / 100 + 1)
+	local capacity=$(expr $procs / $mods + 1)
+	[ "$groups" -gt "$capacity" ] && groups=$capacity
+	local partitions=$(expr $groups \* $mods)
+		
+cat >${script}.sh  <<EOL
+#!/bin/bash
+LANG=$LANG
+shopt -u nocaseglob;shopt -u nocasematch
+
+if [ "\$#" -eq "1" ];then
+	ID=\$1
+else
+	ID=\$SGE_TASK_ID
+fi
+
+ID=\$(expr \$ID - 1)
+m=\$(expr \$ID / $groups )
+leaf=\$(printf %04d \$(expr \$ID % $groups + 1))
+db=$ppath/leaf_\${leaf}.tmpp
+		
+mods=(${modList[*]})
+mod=\${mods[\$m]}
+run="\$(basename \$mod .mod)_\$leaf"
+
+if [[ "\$(basename \$(dirname \$mod))" == "x-rev" ]];then
+	workdir=$ppath/x-rev
+else
+	workdir=$ppath
+fi
+
+cd \$workdir
+$hmmscore \$run -db \$db -modelfile \$mod $HMMSCORE_OPTS
+
+EOL
+	chmod 755 $script.sh
+	$bin/interleavedSamples.pl -X tmpp -G $groups $ppath/${project}_${level}.fas $ppath/leaf > /dev/null 2>&1
+	if [ "$doGrid" -eq "1" ];then
+		# specifying -q all.q may be very important to the success of this call
+		qsub -t 1-$partitions:1 -N ${project}-${level} -sync y -j y -o $script.o $script.sh > /dev/null 2>&1
+		if [ "$?" -ne "0" ];then
+			(( $DO_WEB )) || echo -e "\n\nWARNING: qsub of '$project-$level' failed. Switching to master node.\n\n"
+			$PARALLEL --workdir $ppath -j $LOCAL_PROC $script.sh {} ::: $(seq $partitions) > /dev/null 2>&1
+		else
+			rm ${script}.o
+		fi
+	else
+		$PARALLEL --workdir $ppath -j $LOCAL_PROC $script.sh {} ::: $(seq $partitions) > /dev/null 2>&1
+	fi
+	(( $DO_WEB )) || echo -n '...'
+
+	local mod=""
+	local run=""
+	local pat=""
+	for mod in "${modList[@]}";do
+		run=$(basename $mod .mod)
+		pat=$(basename $(dirname $mod))
+
+		if [[ "$pat" == "x-rev" ]];then
+			$bin/parseScores.pl $ppath/x-rev/${run}_????.dist > $ppath/x-rev/${run}.tab && rm $ppath/x-rev/${run}_????.dist
+		else
+			$bin/parseScores.pl $ppath/${run}_????.dist > $ppath/${run}.tab && rm $ppath/${run}_????.dist
+		fi
+	done
+	rm $ppath/$level.tmp.sh $ppath/*.tmpp $ppath/null_????.dist > /dev/null 2>&1
 
 	local nllArg=""
 	local trnArg=""
@@ -543,7 +480,6 @@ function doAnalysis() {
 		rm $ppath/*.o > /dev/null 2>&1
 		rm $ppath/*_hmm.tab $ppath/*dat $ppath/${project}.log
 		rm $ppath/${project}_${level}.fas 
-		[ -r $mpath/null.mod ] 	&& rm $ppath/null.tab $ppath/null.dist > /dev/null 2>&1
 		[ -d $ppath/x-rev ] 	&& rm -rf $ppath/x-rev
 	fi
 }
@@ -566,10 +502,22 @@ else
 		IS_PIPE=0
 	fi
 
-	cp $inputFasta $ppath/${project}_${level}.fas
-	$bin/stripSequences.pl -F  $ppath/${project}_$level.fas '0-9 :~.-' > $ppath/${project}_$level.fas2
-	perl $bin/removeByRedundantHeader.pl $ppath/${project}_$level.fas2 > $ppath/${project}_$level.fas
+	$bin/stripSequences.pl -F $inputFasta '0-9 :~.-' | $bin/removeByRedundantHeader.pl > $ppath/${project}_$level.fas
 	cp $ppath/${project}_$level.fas $ppath/${project}_$level.fas2
+
+
+	if [ "$USE_SGE" -eq "1" ];then
+		AVG_LEN=$(expr $(grep -v '>' $ppath/${project}_$level.fas|wc -c) / $(grep '>' $ppath/${project}_$level.fas -c) + 1)
+		if [ "$AVG_LEN" -le 300 ];then
+			SEQ_LIMIT=1600
+		elif [ "$AVG_LEN" -le 1000 ];then
+			SEQ_LIMIT=400
+		elif [ "$AVG_LEN" -le 1800 ];then
+			SEQ_LIMIT=100
+		else
+			SEQ_LIMIT=50
+		fi
+	fi
 fi
 
 # START MAIN #
@@ -653,7 +601,6 @@ cd $owd
 cp $bpath/$resources/README.rtf $ppath
 (( $DO_WEB )) || $bin/evaluateResults.pl -H -S $ppath/${project}_final.txt
 
-
 if [ $NO_DELETE -eq 0 ];then
 	rm $ppath/*tmp
 fi
@@ -670,7 +617,7 @@ if [ $DO_ALIGNMENT -eq 1 -a $DO_CONTROL -eq 1 ];then
 	(( $DO_WEB )) || echo "LABEL: Performing alignments."
 	if [ -r "$tnpath/x-control/control.mod" ];then
 		doAlignment $ppath/FASTA/${project}_reannotated.fas $ppath/FASTA/${project}_ordered.fasta $module &
-		$bin/interleavedSamples.pl -G $P $ppath/FASTA/${project}_predictions.fas $ppath/FASTA/${module}_control -X tmp >/dev/null 2>&1
+		$bin/interleavedSamples.pl -G $LOCAL_PROC $ppath/FASTA/${project}_predictions.fas $ppath/FASTA/${module}_control -X tmp >/dev/null 2>&1
 		for sample in $ppath/FASTA/${module}_control*tmp;do
 			doHMMalignment $sample `basename $sample`.fasta $tnpath/x-control/control.mod &
 		done
@@ -716,7 +663,7 @@ else
 		(( $DO_WEB )) || echo "LABEL: Aligning control datasets."
 
 		if [ -r "$tnpath/x-control/control.mod" ];then
-			$bin/interleavedSamples.pl -G $P $ppath/FASTA/${project}_predictions.fas $ppath/FASTA/${module}_control -X tmp >/dev/null 2>&1
+			$bin/interleavedSamples.pl -G $LOCAL_PROC $ppath/FASTA/${project}_predictions.fas $ppath/FASTA/${module}_control -X tmp >/dev/null 2>&1
 			for sample in $ppath/FASTA/${module}_control*tmp;do
 				doHMMalignment $sample `basename $sample`.fasta $tnpath/x-control/control.mod &
 			done
